@tool
extends SceneTree

func _init():
	print("--- Criando/Atualizando Materiais BotW Calibrados no Godot 4.7.2 ---")
	var dir = DirAccess.open("res://")
	if not dir.dir_exists("materials"):
		dir.make_dir("materials")

	var cel_shader = ResourceLoader.load("res://shaders/botw_cel.gdshader")
	var foliage_shader = ResourceLoader.load("res://shaders/botw_foliage.gdshader")
	var grass_shader = ResourceLoader.load("res://shaders/botw_grass.gdshader")
	var water_shader = ResourceLoader.load("res://shaders/botw_water.gdshader")
	var sky_shader = ResourceLoader.load("res://shaders/botw_sky.gdshader")

	# 1. m_botw_cel_default.tres
	var mat_default = ShaderMaterial.new()
	mat_default.shader = cel_shader
	mat_default.set_shader_parameter("albedo_color", Color(0.92, 0.90, 0.85, 1.0))
	mat_default.set_shader_parameter("shadow_tint", Color(0.28, 0.38, 0.58, 1.0))
	mat_default.set_shader_parameter("shadow_saturation", 1.1)
	mat_default.set_shader_parameter("midtone_tint", Color(0.78, 0.85, 0.92, 1.0))
	mat_default.set_shader_parameter("shadow_cut_mid", 0.35)
	mat_default.set_shader_parameter("shadow_cut_bright", 0.70)
	mat_default.set_shader_parameter("shadow_smoothness", 0.035)
	mat_default.set_shader_parameter("ao_strength", 0.4)
	mat_default.set_shader_parameter("rim_color", Color(0.75, 0.90, 1.0, 1.0))
	mat_default.set_shader_parameter("rim_power", 3.2)
	mat_default.set_shader_parameter("rim_intensity", 0.75)
	mat_default.set_shader_parameter("rim_smoothness", 0.06)
	mat_default.set_shader_parameter("rim_ambient_silhouette", 0.30)
	mat_default.set_shader_parameter("specular_color", Color(1.0, 1.0, 1.0, 1.0))
	mat_default.set_shader_parameter("specular_size", 0.05)
	mat_default.set_shader_parameter("specular_smoothness", 0.012)
	mat_default.set_shader_parameter("glint_intensity", 1.6)
	mat_default.set_shader_parameter("roughness_value", 0.75)
	var err1 = ResourceSaver.save(mat_default, "res://materials/m_botw_cel_default.tres")
	print("Salvando m_botw_cel_default.tres: ", err1 == OK)

	# 2. m_botw_cel_character.tres
	var mat_char = ShaderMaterial.new()
	mat_char.shader = cel_shader
	mat_char.set_shader_parameter("albedo_color", Color(1.0, 0.92, 0.86, 1.0))
	mat_char.set_shader_parameter("shadow_tint", Color(0.35, 0.40, 0.60, 1.0))
	mat_char.set_shader_parameter("shadow_saturation", 1.15)
	mat_char.set_shader_parameter("midtone_tint", Color(0.88, 0.86, 0.90, 1.0))
	mat_char.set_shader_parameter("shadow_cut_mid", 0.32)
	mat_char.set_shader_parameter("shadow_cut_bright", 0.68)
	mat_char.set_shader_parameter("shadow_smoothness", 0.04)
	mat_char.set_shader_parameter("ao_strength", 0.35)
	mat_char.set_shader_parameter("rim_color", Color(0.85, 0.95, 1.0, 1.0))
	mat_char.set_shader_parameter("rim_power", 2.8)
	mat_char.set_shader_parameter("rim_intensity", 0.95)
	mat_char.set_shader_parameter("rim_smoothness", 0.05)
	mat_char.set_shader_parameter("rim_ambient_silhouette", 0.40)
	mat_char.set_shader_parameter("specular_color", Color(1.0, 0.98, 0.95, 1.0))
	mat_char.set_shader_parameter("specular_size", 0.04)
	mat_char.set_shader_parameter("specular_smoothness", 0.01)
	mat_char.set_shader_parameter("glint_intensity", 1.8)
	mat_char.set_shader_parameter("roughness_value", 0.6)
	var err2 = ResourceSaver.save(mat_char, "res://materials/m_botw_cel_character.tres")
	print("Salvando m_botw_cel_character.tres: ", err2 == OK)

	# 3. m_botw_cel_rock.tres
	var mat_rock = ShaderMaterial.new()
	mat_rock.shader = cel_shader
	mat_rock.set_shader_parameter("albedo_color", Color(0.55, 0.52, 0.48, 1.0))
	mat_rock.set_shader_parameter("shadow_tint", Color(0.22, 0.32, 0.48, 1.0))
	mat_rock.set_shader_parameter("shadow_saturation", 1.2)
	mat_rock.set_shader_parameter("midtone_tint", Color(0.68, 0.72, 0.78, 1.0))
	mat_rock.set_shader_parameter("shadow_cut_mid", 0.38)
	mat_rock.set_shader_parameter("shadow_cut_bright", 0.74)
	mat_rock.set_shader_parameter("shadow_smoothness", 0.035)
	mat_rock.set_shader_parameter("ao_strength", 0.6)
	mat_rock.set_shader_parameter("rim_color", Color(0.70, 0.82, 0.95, 1.0))
	mat_rock.set_shader_parameter("rim_power", 3.8)
	mat_rock.set_shader_parameter("rim_intensity", 0.55)
	mat_rock.set_shader_parameter("rim_smoothness", 0.06)
	mat_rock.set_shader_parameter("rim_ambient_silhouette", 0.25)
	mat_rock.set_shader_parameter("specular_color", Color(0.9, 0.92, 0.95, 1.0))
	mat_rock.set_shader_parameter("specular_size", 0.02)
	mat_rock.set_shader_parameter("specular_smoothness", 0.01)
	mat_rock.set_shader_parameter("glint_intensity", 1.2)
	mat_rock.set_shader_parameter("roughness_value", 0.88)
	var err3 = ResourceSaver.save(mat_rock, "res://materials/m_botw_cel_rock.tres")
	print("Salvando m_botw_cel_rock.tres: ", err3 == OK)

	# 4. m_botw_foliage.tres
	var mat_foliage = ShaderMaterial.new()
	mat_foliage.shader = foliage_shader
	mat_foliage.set_shader_parameter("albedo_color", Color(0.42, 0.72, 0.22, 1.0))
	mat_foliage.set_shader_parameter("top_tint", Color(0.62, 0.88, 0.26, 1.0))
	mat_foliage.set_shader_parameter("bottom_tint", Color(0.18, 0.42, 0.16, 1.0))
	mat_foliage.set_shader_parameter("vertical_gradient_power", 1.2)
	mat_foliage.set_shader_parameter("cluster_center_offset", Vector3(0.0, 3.8, 0.0))
	mat_foliage.set_shader_parameter("spherical_normal_strength", 0.85)
	mat_foliage.set_shader_parameter("wind_direction", Vector2(1.0, 0.5))
	mat_foliage.set_shader_parameter("wind_speed", 1.8)
	mat_foliage.set_shader_parameter("wind_strength", 0.20)
	mat_foliage.set_shader_parameter("wind_frequency", 0.35)
	mat_foliage.set_shader_parameter("wind_gust_strength", 0.35)
	mat_foliage.set_shader_parameter("wind_gust_speed", 0.9)
	mat_foliage.set_shader_parameter("flutter_speed", 8.0)
	mat_foliage.set_shader_parameter("flutter_strength", 0.045)
	mat_foliage.set_shader_parameter("sway_height_min", 0.3)
	mat_foliage.set_shader_parameter("shadow_tint", Color(0.14, 0.30, 0.38, 1.0))
	mat_foliage.set_shader_parameter("midtone_tint", Color(0.68, 0.84, 0.62, 1.0))
	mat_foliage.set_shader_parameter("shadow_cut_mid", 0.30)
	mat_foliage.set_shader_parameter("shadow_cut_bright", 0.65)
	mat_foliage.set_shader_parameter("shadow_smoothness", 0.04)
	mat_foliage.set_shader_parameter("transmission_color", Color(0.62, 0.92, 0.24, 1.0))
	mat_foliage.set_shader_parameter("transmission_strength", 1.2)
	mat_foliage.set_shader_parameter("transmission_power", 3.5)
	mat_foliage.set_shader_parameter("rim_color", Color(0.85, 0.96, 0.65, 1.0))
	mat_foliage.set_shader_parameter("rim_power", 3.0)
	mat_foliage.set_shader_parameter("rim_intensity", 0.65)
	mat_foliage.set_shader_parameter("rim_ambient_silhouette", 0.25)
	var err4 = ResourceSaver.save(mat_foliage, "res://materials/m_botw_foliage.tres")
	print("Salvando m_botw_foliage.tres: ", err4 == OK)

	# 5. m_botw_grass.tres (mantido e calibrado)
	var mat_grass = ShaderMaterial.new()
	mat_grass.shader = grass_shader
	mat_grass.set_shader_parameter("color_root", Color(0.11, 0.32, 0.10, 1.0))
	mat_grass.set_shader_parameter("color_tip", Color(0.58, 0.88, 0.20, 1.0))
	mat_grass.set_shader_parameter("gradient_power", 1.15)
	mat_grass.set_shader_parameter("wind_direction", Vector2(1.0, 0.3))
	mat_grass.set_shader_parameter("wind_speed", 2.2)
	mat_grass.set_shader_parameter("wind_strength", 0.28)
	mat_grass.set_shader_parameter("wind_scale", 0.12)
	mat_grass.set_shader_parameter("wind_gust_strength", 0.15)
	mat_grass.set_shader_parameter("wind_gust_speed", 1.2)
	mat_grass.set_shader_parameter("wind_vertical_depression", 0.35)
	mat_grass.set_shader_parameter("player_bend_radius", 1.5)
	mat_grass.set_shader_parameter("player_bend_strength", 0.6)
	mat_grass.set_shader_parameter("shadow_tint", Color(0.15, 0.28, 0.38, 1.0))
	mat_grass.set_shader_parameter("midtone_tint", Color(0.70, 0.85, 0.58, 1.0))
	mat_grass.set_shader_parameter("transmission_color", Color(0.48, 0.82, 0.18, 1.0))
	mat_grass.set_shader_parameter("transmission_strength", 0.85)
	var err5 = ResourceSaver.save(mat_grass, "res://materials/m_botw_grass.tres")
	print("Salvando m_botw_grass.tres: ", err5 == OK)

	# 6. m_botw_water.tres
	var mat_water = ShaderMaterial.new()
	mat_water.shader = water_shader
	mat_water.set_shader_parameter("shallow_color", Color(0.18, 0.86, 0.80, 0.72))
	mat_water.set_shader_parameter("mid_color", Color(0.08, 0.52, 0.74, 0.88))
	mat_water.set_shader_parameter("deep_color", Color(0.02, 0.16, 0.46, 0.96))
	mat_water.set_shader_parameter("depth_distance", 4.5)
	mat_water.set_shader_parameter("depth_curve", 1.25)
	mat_water.set_shader_parameter("foam_color", Color(0.97, 1.0, 1.0, 1.0))
	mat_water.set_shader_parameter("foam_width", 0.55)
	mat_water.set_shader_parameter("foam_surge_intensity", 0.45)
	mat_water.set_shader_parameter("foam_smoothness", 0.04)
	mat_water.set_shader_parameter("foam_speed", 1.4)
	mat_water.set_shader_parameter("foam_noise_scale", 16.0)
	mat_water.set_shader_parameter("wave_speed", 1.3)
	mat_water.set_shader_parameter("wave_amplitude", 0.09)
	mat_water.set_shader_parameter("wave_frequency", 1.35)
	mat_water.set_shader_parameter("caustics_color", Color(0.75, 0.98, 1.0, 0.65))
	mat_water.set_shader_parameter("caustics_scale", 2.2)
	mat_water.set_shader_parameter("caustics_speed", 0.85)
	mat_water.set_shader_parameter("caustics_strength", 0.55)
	mat_water.set_shader_parameter("caustics_fade_depth", 5.0)
	mat_water.set_shader_parameter("roughness", 0.06)
	mat_water.set_shader_parameter("specular_strength", 1.4)
	mat_water.set_shader_parameter("sun_specular_color", Color(1.0, 0.98, 0.88, 1.0))
	mat_water.set_shader_parameter("fresnel_power", 4.0)
	var err6 = ResourceSaver.save(mat_water, "res://materials/m_botw_water.tres")
	print("Salvando m_botw_water.tres: ", err6 == OK)

	# 7. m_botw_sky.tres
	var mat_sky = ShaderMaterial.new()
	mat_sky.shader = sky_shader
	mat_sky.set_shader_parameter("use_light_direction", false)
	mat_sky.set_shader_parameter("time_of_day", 12.0)
	mat_sky.set_shader_parameter("dawn_zenith", Color(0.36, 0.42, 0.70, 1.0))
	mat_sky.set_shader_parameter("dawn_horizon", Color(0.98, 0.68, 0.36, 1.0))
	mat_sky.set_shader_parameter("dawn_haze", Color(1.0, 0.80, 0.54, 1.0))
	mat_sky.set_shader_parameter("noon_zenith", Color(0.14, 0.48, 0.90, 1.0))
	mat_sky.set_shader_parameter("noon_horizon", Color(0.64, 0.84, 0.96, 1.0))
	mat_sky.set_shader_parameter("noon_haze", Color(0.82, 0.94, 1.00, 1.0))
	mat_sky.set_shader_parameter("sunset_zenith", Color(0.24, 0.14, 0.44, 1.0))
	mat_sky.set_shader_parameter("sunset_horizon", Color(0.98, 0.38, 0.16, 1.0))
	mat_sky.set_shader_parameter("sunset_haze", Color(0.99, 0.54, 0.26, 1.0))
	mat_sky.set_shader_parameter("night_zenith", Color(0.012, 0.022, 0.075, 1.0))
	mat_sky.set_shader_parameter("night_horizon", Color(0.045, 0.075, 0.16, 1.0))
	mat_sky.set_shader_parameter("night_haze", Color(0.07, 0.11, 0.22, 1.0))
	mat_sky.set_shader_parameter("ground_color", Color(0.06, 0.08, 0.07, 1.0))
	mat_sky.set_shader_parameter("horizon_haze_intensity", 0.68)
	mat_sky.set_shader_parameter("horizon_haze_exponent", 2.8)
	mat_sky.set_shader_parameter("sun_color", Color(1.0, 0.96, 0.86, 1.0))
	mat_sky.set_shader_parameter("sun_disk_size", 0.016)
	mat_sky.set_shader_parameter("sun_disk_smoothness", 0.002)
	mat_sky.set_shader_parameter("sun_corona_size", 45.0)
	mat_sky.set_shader_parameter("moon_color", Color(0.85, 0.92, 1.0, 1.0))
	mat_sky.set_shader_parameter("moon_disk_size", 0.013)
	mat_sky.set_shader_parameter("star_density", 0.003)
	mat_sky.set_shader_parameter("star_scale", 220.0)
	mat_sky.set_shader_parameter("star_twinkle_speed", 3.2)
	mat_sky.set_shader_parameter("star_intensity", 2.2)
	mat_sky.set_shader_parameter("enable_clouds", true)
	mat_sky.set_shader_parameter("cloud_color_lit", Color(1.0, 0.99, 0.96, 1.0))
	mat_sky.set_shader_parameter("cloud_color_shadow", Color(0.68, 0.74, 0.86, 1.0))
	mat_sky.set_shader_parameter("cloud_crest_tint", Color(1.0, 0.95, 0.80, 1.0))
	mat_sky.set_shader_parameter("cloud_coverage", 0.50)
	mat_sky.set_shader_parameter("cloud_softness", 0.14)
	mat_sky.set_shader_parameter("cloud_speed", 0.045)
	mat_sky.set_shader_parameter("cloud_scale", 1.0)
	mat_sky.set_shader_parameter("cloud_crest_intensity", 1.4)
	mat_sky.set_shader_parameter("cloud_direction", Vector2(1.0, 0.35))
	var err7 = ResourceSaver.save(mat_sky, "res://materials/m_botw_sky.tres")
	print("Salvando m_botw_sky.tres: ", err7 == OK)

	# 8. m_botw_cel_link_tunic.tres
	var mat_tunic = ShaderMaterial.new()
	mat_tunic.shader = cel_shader
	mat_tunic.set_shader_parameter("albedo_color", Color(0.12, 0.58, 0.86, 1.0))
	mat_tunic.set_shader_parameter("shadow_tint", Color(0.18, 0.26, 0.46, 1.0))
	mat_tunic.set_shader_parameter("shadow_saturation", 1.15)
	mat_tunic.set_shader_parameter("midtone_tint", Color(0.48, 0.72, 0.92, 1.0))
	mat_tunic.set_shader_parameter("shadow_cut_mid", 0.32)
	mat_tunic.set_shader_parameter("shadow_cut_bright", 0.68)
	mat_tunic.set_shader_parameter("shadow_smoothness", 0.04)
	mat_tunic.set_shader_parameter("ao_strength", 0.35)
	mat_tunic.set_shader_parameter("rim_color", Color(0.80, 0.95, 1.0, 1.0))
	mat_tunic.set_shader_parameter("rim_power", 2.6)
	mat_tunic.set_shader_parameter("rim_intensity", 0.95)
	mat_tunic.set_shader_parameter("rim_smoothness", 0.05)
	mat_tunic.set_shader_parameter("rim_ambient_silhouette", 0.40)
	mat_tunic.set_shader_parameter("specular_color", Color(1.0, 1.0, 1.0, 1.0))
	mat_tunic.set_shader_parameter("specular_size", 0.04)
	mat_tunic.set_shader_parameter("glint_intensity", 1.5)
	mat_tunic.set_shader_parameter("roughness_value", 0.65)
	var err8 = ResourceSaver.save(mat_tunic, "res://materials/m_botw_cel_link_tunic.tres")
	print("Salvando m_botw_cel_link_tunic.tres: ", err8 == OK)

	# 9. m_botw_cel_goblin.tres
	var mat_goblin = ShaderMaterial.new()
	mat_goblin.shader = cel_shader
	mat_goblin.set_shader_parameter("albedo_color", Color(0.38, 0.65, 0.28, 1.0))
	mat_goblin.set_shader_parameter("shadow_tint", Color(0.18, 0.28, 0.44, 1.0))
	mat_goblin.set_shader_parameter("shadow_saturation", 1.15)
	mat_goblin.set_shader_parameter("midtone_tint", Color(0.70, 0.85, 0.60, 1.0))
	mat_goblin.set_shader_parameter("shadow_cut_mid", 0.32)
	mat_goblin.set_shader_parameter("shadow_cut_bright", 0.68)
	mat_goblin.set_shader_parameter("shadow_smoothness", 0.04)
	mat_goblin.set_shader_parameter("ao_strength", 0.4)
	mat_goblin.set_shader_parameter("rim_color", Color(0.80, 0.95, 0.70, 1.0))
	mat_goblin.set_shader_parameter("rim_power", 2.6)
	mat_goblin.set_shader_parameter("rim_intensity", 0.90)
	mat_goblin.set_shader_parameter("rim_smoothness", 0.06)
	mat_goblin.set_shader_parameter("rim_ambient_silhouette", 0.35)
	mat_goblin.set_shader_parameter("specular_color", Color(0.9, 1.0, 0.8, 1.0))
	mat_goblin.set_shader_parameter("specular_size", 0.04)
	mat_goblin.set_shader_parameter("glint_intensity", 1.4)
	mat_goblin.set_shader_parameter("roughness_value", 0.65)
	var err9 = ResourceSaver.save(mat_goblin, "res://materials/m_botw_cel_goblin.tres")
	print("Salvando m_botw_cel_goblin.tres: ", err9 == OK)

	# 10. m_botw_cel_birch_bark.tres
	var mat_birch_bark = ShaderMaterial.new()
	mat_birch_bark.shader = cel_shader
	mat_birch_bark.set_shader_parameter("albedo_color", Color(0.96, 0.95, 0.92, 1.0))
	mat_birch_bark.set_shader_parameter("shadow_tint", Color(0.28, 0.38, 0.58, 1.0))
	mat_birch_bark.set_shader_parameter("shadow_saturation", 1.1)
	mat_birch_bark.set_shader_parameter("midtone_tint", Color(0.85, 0.88, 0.92, 1.0))
	mat_birch_bark.set_shader_parameter("shadow_cut_mid", 0.35)
	mat_birch_bark.set_shader_parameter("shadow_cut_bright", 0.70)
	mat_birch_bark.set_shader_parameter("shadow_smoothness", 0.035)
	mat_birch_bark.set_shader_parameter("ao_strength", 0.45)
	mat_birch_bark.set_shader_parameter("rim_color", Color(0.85, 0.94, 1.0, 1.0))
	mat_birch_bark.set_shader_parameter("rim_power", 2.8)
	mat_birch_bark.set_shader_parameter("rim_intensity", 0.85)
	mat_birch_bark.set_shader_parameter("rim_smoothness", 0.06)
	mat_birch_bark.set_shader_parameter("rim_ambient_silhouette", 0.30)
	mat_birch_bark.set_shader_parameter("specular_color", Color(1.0, 1.0, 1.0, 1.0))
	mat_birch_bark.set_shader_parameter("specular_size", 0.04)
	mat_birch_bark.set_shader_parameter("glint_intensity", 1.4)
	mat_birch_bark.set_shader_parameter("roughness_value", 0.75)
	var err10 = ResourceSaver.save(mat_birch_bark, "res://materials/m_botw_cel_birch_bark.tres")
	print("Salvando m_botw_cel_birch_bark.tres: ", err10 == OK)

	# 11. m_botw_cel_birch_stripes.tres
	var mat_birch_stripes = ShaderMaterial.new()
	mat_birch_stripes.shader = cel_shader
	mat_birch_stripes.set_shader_parameter("albedo_color", Color(0.16, 0.16, 0.18, 1.0))
	mat_birch_stripes.set_shader_parameter("shadow_tint", Color(0.10, 0.12, 0.20, 1.0))
	mat_birch_stripes.set_shader_parameter("shadow_saturation", 1.1)
	mat_birch_stripes.set_shader_parameter("midtone_tint", Color(0.30, 0.32, 0.38, 1.0))
	mat_birch_stripes.set_shader_parameter("shadow_cut_mid", 0.35)
	mat_birch_stripes.set_shader_parameter("shadow_cut_bright", 0.70)
	mat_birch_stripes.set_shader_parameter("shadow_smoothness", 0.035)
	mat_birch_stripes.set_shader_parameter("ao_strength", 0.5)
	mat_birch_stripes.set_shader_parameter("rim_color", Color(0.70, 0.82, 0.95, 1.0))
	mat_birch_stripes.set_shader_parameter("rim_power", 3.2)
	mat_birch_stripes.set_shader_parameter("rim_intensity", 0.50)
	mat_birch_stripes.set_shader_parameter("rim_smoothness", 0.06)
	mat_birch_stripes.set_shader_parameter("rim_ambient_silhouette", 0.25)
	mat_birch_stripes.set_shader_parameter("specular_size", 0.02)
	mat_birch_stripes.set_shader_parameter("glint_intensity", 1.0)
	mat_birch_stripes.set_shader_parameter("roughness_value", 0.80)
	var err11 = ResourceSaver.save(mat_birch_stripes, "res://materials/m_botw_cel_birch_stripes.tres")
	print("Salvando m_botw_cel_birch_stripes.tres: ", err11 == OK)

	print("Finalizado com sucesso! Todos os 11 materiais foram atualizados.")
	quit(0)
