@tool
extends SceneTree

func _init():
	print("--- Criando Materiais BotW no Godot 4.7.2 ---")
	var dir = DirAccess.open("res://")
	if not dir.dir_exists("materials"):
		dir.make_dir("materials")

	var cel_shader = ResourceLoader.load("res://shaders/botw_cel.gdshader")
	var foliage_shader = ResourceLoader.load("res://shaders/botw_foliage.gdshader")
	var grass_shader = ResourceLoader.load("res://shaders/botw_grass.gdshader")
	var water_shader = ResourceLoader.load("res://shaders/botw_water.gdshader")
	var sky_shader = ResourceLoader.load("res://shaders/botw_sky.gdshader")

	# 1. m_botw_cel_default.tres
	var mat_default = ShaderMaterial.new()
	mat_default.shader = cel_shader
	mat_default.set_shader_parameter("albedo_color", Color(0.92, 0.90, 0.85, 1.0))
	mat_default.set_shader_parameter("shadow_tint", Color(0.28, 0.38, 0.58, 1.0))
	mat_default.set_shader_parameter("midtone_tint", Color(0.78, 0.85, 0.92, 1.0))
	mat_default.set_shader_parameter("shadow_cut_mid", 0.35)
	mat_default.set_shader_parameter("shadow_cut_bright", 0.70)
	mat_default.set_shader_parameter("shadow_smoothness", 0.04)
	mat_default.set_shader_parameter("rim_color", Color(0.75, 0.90, 1.0, 1.0))
	mat_default.set_shader_parameter("rim_power", 3.5)
	mat_default.set_shader_parameter("rim_intensity", 0.65)
	mat_default.set_shader_parameter("rim_smoothness", 0.08)
	mat_default.set_shader_parameter("specular_color", Color(1.0, 1.0, 1.0, 1.0))
	mat_default.set_shader_parameter("specular_size", 0.05)
	mat_default.set_shader_parameter("roughness_value", 0.75)
	var err1 = ResourceSaver.save(mat_default, "res://materials/m_botw_cel_default.tres")
	print("Salvando m_botw_cel_default.tres: ", err1 == OK)

	# 2. m_botw_cel_character.tres
	var mat_char = ShaderMaterial.new()
	mat_char.shader = cel_shader
	mat_char.set_shader_parameter("albedo_color", Color(1.0, 0.92, 0.86, 1.0))
	mat_char.set_shader_parameter("shadow_tint", Color(0.35, 0.40, 0.60, 1.0)) # Ceruleo com calor sutil
	mat_char.set_shader_parameter("midtone_tint", Color(0.88, 0.86, 0.90, 1.0))
	mat_char.set_shader_parameter("shadow_cut_mid", 0.32)
	mat_char.set_shader_parameter("shadow_cut_bright", 0.68)
	mat_char.set_shader_parameter("shadow_smoothness", 0.05)
	mat_char.set_shader_parameter("rim_color", Color(0.85, 0.95, 1.0, 1.0))
	mat_char.set_shader_parameter("rim_power", 2.8)
	mat_char.set_shader_parameter("rim_intensity", 0.85) # Rim light forte para destacar personagens
	mat_char.set_shader_parameter("rim_smoothness", 0.06)
	mat_char.set_shader_parameter("specular_color", Color(1.0, 0.98, 0.95, 1.0))
	mat_char.set_shader_parameter("specular_size", 0.04)
	mat_char.set_shader_parameter("roughness_value", 0.6)
	var err2 = ResourceSaver.save(mat_char, "res://materials/m_botw_cel_character.tres")
	print("Salvando m_botw_cel_character.tres: ", err2 == OK)

	# 3. m_botw_cel_rock.tres
	var mat_rock = ShaderMaterial.new()
	mat_rock.shader = cel_shader
	mat_rock.set_shader_parameter("albedo_color", Color(0.55, 0.52, 0.48, 1.0))
	mat_rock.set_shader_parameter("shadow_tint", Color(0.22, 0.32, 0.48, 1.0))
	mat_rock.set_shader_parameter("midtone_tint", Color(0.68, 0.72, 0.78, 1.0))
	mat_rock.set_shader_parameter("shadow_cut_mid", 0.40)
	mat_rock.set_shader_parameter("shadow_cut_bright", 0.75)
	mat_rock.set_shader_parameter("shadow_smoothness", 0.03)
	mat_rock.set_shader_parameter("rim_color", Color(0.70, 0.82, 0.95, 1.0))
	mat_rock.set_shader_parameter("rim_power", 4.0)
	mat_rock.set_shader_parameter("rim_intensity", 0.45)
	mat_rock.set_shader_parameter("specular_size", 0.02)
	mat_rock.set_shader_parameter("roughness_value", 0.9)
	var err3 = ResourceSaver.save(mat_rock, "res://materials/m_botw_cel_rock.tres")
	print("Salvando m_botw_cel_rock.tres: ", err3 == OK)

	# 4. m_botw_foliage.tres
	var mat_foliage = ShaderMaterial.new()
	mat_foliage.shader = foliage_shader
	mat_foliage.set_shader_parameter("albedo_color", Color(0.42, 0.72, 0.22, 1.0))
	mat_foliage.set_shader_parameter("top_tint", Color(0.62, 0.88, 0.26, 1.0))
	mat_foliage.set_shader_parameter("bottom_tint", Color(0.18, 0.42, 0.16, 1.0))
	mat_foliage.set_shader_parameter("vertical_gradient_power", 1.2)
	mat_foliage.set_shader_parameter("cluster_center_offset", Vector3(0.0, 1.8, 0.0))
	mat_foliage.set_shader_parameter("spherical_normal_strength", 0.85)
	mat_foliage.set_shader_parameter("wind_direction", Vector2(1.0, 0.5))
	mat_foliage.set_shader_parameter("wind_speed", 1.8)
	mat_foliage.set_shader_parameter("wind_strength", 0.18)
	mat_foliage.set_shader_parameter("flutter_speed", 6.0)
	mat_foliage.set_shader_parameter("flutter_strength", 0.04)
	mat_foliage.set_shader_parameter("shadow_tint", Color(0.14, 0.30, 0.38, 1.0))
	mat_foliage.set_shader_parameter("midtone_tint", Color(0.68, 0.84, 0.62, 1.0))
	mat_foliage.set_shader_parameter("transmission_color", Color(0.58, 0.88, 0.24, 1.0))
	mat_foliage.set_shader_parameter("transmission_strength", 0.8)
	mat_foliage.set_shader_parameter("rim_color", Color(0.85, 0.96, 0.65, 1.0))
	mat_foliage.set_shader_parameter("rim_power", 3.0)
	mat_foliage.set_shader_parameter("rim_intensity", 0.55)
	var err4 = ResourceSaver.save(mat_foliage, "res://materials/m_botw_foliage.tres")
	print("Salvando m_botw_foliage.tres: ", err4 == OK)

	# 5. m_botw_grass.tres
	var mat_grass = ShaderMaterial.new()
	mat_grass.shader = grass_shader
	mat_grass.set_shader_parameter("color_root", Color(0.11, 0.32, 0.10, 1.0))
	mat_grass.set_shader_parameter("color_tip", Color(0.58, 0.88, 0.20, 1.0))
	mat_grass.set_shader_parameter("gradient_power", 1.15)
	mat_grass.set_shader_parameter("wind_direction", Vector2(1.0, 0.3))
	mat_grass.set_shader_parameter("wind_speed", 2.2)
	mat_grass.set_shader_parameter("wind_strength", 0.28)
	mat_grass.set_shader_parameter("wind_scale", 0.12)
	mat_grass.set_shader_parameter("wind_gust_strength", 0.15)
	mat_grass.set_shader_parameter("wind_gust_speed", 1.2)
	mat_grass.set_shader_parameter("wind_vertical_depression", 0.35)
	mat_grass.set_shader_parameter("player_bend_radius", 1.5)
	mat_grass.set_shader_parameter("player_bend_strength", 0.6)
	mat_grass.set_shader_parameter("shadow_tint", Color(0.15, 0.28, 0.38, 1.0))
	mat_grass.set_shader_parameter("midtone_tint", Color(0.70, 0.85, 0.58, 1.0))
	mat_grass.set_shader_parameter("transmission_color", Color(0.48, 0.82, 0.18, 1.0))
	mat_grass.set_shader_parameter("transmission_strength", 0.85)
	var err5 = ResourceSaver.save(mat_grass, "res://materials/m_botw_grass.tres")
	print("Salvando m_botw_grass.tres: ", err5 == OK)

	# 6. m_botw_water.tres
	var mat_water = ShaderMaterial.new()
	mat_water.shader = water_shader
	mat_water.set_shader_parameter("shallow_color", Color(0.18, 0.82, 0.78, 0.75))
	mat_water.set_shader_parameter("deep_color", Color(0.04, 0.25, 0.52, 0.95))
	mat_water.set_shader_parameter("depth_distance", 3.5)
	mat_water.set_shader_parameter("foam_color", Color(0.96, 1.0, 1.0, 1.0))
	mat_water.set_shader_parameter("foam_width", 0.45)
	mat_water.set_shader_parameter("foam_smoothness", 0.06)
	mat_water.set_shader_parameter("foam_speed", 1.5)
	mat_water.set_shader_parameter("foam_noise_scale", 18.0)
	mat_water.set_shader_parameter("wave_speed", 1.2)
	mat_water.set_shader_parameter("wave_amplitude", 0.08)
	mat_water.set_shader_parameter("wave_frequency", 1.4)
	mat_water.set_shader_parameter("caustics_color", Color(0.70, 0.95, 1.0, 0.5))
	mat_water.set_shader_parameter("caustics_scale", 2.0)
	mat_water.set_shader_parameter("caustics_speed", 0.8)
	mat_water.set_shader_parameter("caustics_strength", 0.35)
	mat_water.set_shader_parameter("roughness", 0.08)
	mat_water.set_shader_parameter("specular_strength", 1.0)
	mat_water.set_shader_parameter("sun_specular_color", Color(1.0, 0.98, 0.85, 1.0))
	var err6 = ResourceSaver.save(mat_water, "res://materials/m_botw_water.tres")
	print("Salvando m_botw_water.tres: ", err6 == OK)

	# 7. m_botw_sky.tres
	var mat_sky = ShaderMaterial.new()
	mat_sky.shader = sky_shader
	mat_sky.set_shader_parameter("use_light_direction", true)
	mat_sky.set_shader_parameter("time_of_day", 12.0)
	mat_sky.set_shader_parameter("dawn_zenith", Vector3(0.35, 0.42, 0.68))
	mat_sky.set_shader_parameter("dawn_horizon", Vector3(0.98, 0.65, 0.38))
	mat_sky.set_shader_parameter("dawn_haze", Vector3(1.0, 0.78, 0.52))
	mat_sky.set_shader_parameter("noon_zenith", Vector3(0.16, 0.48, 0.88))
	mat_sky.set_shader_parameter("noon_horizon", Vector3(0.62, 0.82, 0.94))
	mat_sky.set_shader_parameter("noon_haze", Vector3(0.80, 0.92, 1.00))
	mat_sky.set_shader_parameter("sunset_zenith", Vector3(0.22, 0.16, 0.42))
	mat_sky.set_shader_parameter("sunset_horizon", Vector3(0.96, 0.38, 0.18))
	mat_sky.set_shader_parameter("sunset_haze", Vector3(0.98, 0.52, 0.28))
	mat_sky.set_shader_parameter("night_zenith", Vector3(0.015, 0.025, 0.08))
	mat_sky.set_shader_parameter("night_horizon", Vector3(0.05, 0.08, 0.16))
	mat_sky.set_shader_parameter("night_haze", Vector3(0.08, 0.12, 0.22))
	mat_sky.set_shader_parameter("horizon_haze_intensity", 0.65)
	mat_sky.set_shader_parameter("horizon_haze_exponent", 3.0)
	mat_sky.set_shader_parameter("sun_color", Vector3(1.0, 0.95, 0.85))
	mat_sky.set_shader_parameter("sun_disk_size", 0.015)
	mat_sky.set_shader_parameter("star_density", 0.0025)
	mat_sky.set_shader_parameter("enable_clouds", true)
	mat_sky.set_shader_parameter("cloud_coverage", 0.52)
	mat_sky.set_shader_parameter("cloud_softness", 0.12)
	mat_sky.set_shader_parameter("cloud_speed", 0.04)
	var err7 = ResourceSaver.save(mat_sky, "res://materials/m_botw_sky.tres")
	print("Salvando m_botw_sky.tres: ", err7 == OK)

	print("Finalizado com sucesso!")
	quit(0)
